env:
  browser: true
  es2021: true
  commonjs: true
  jest: true # Add the 'jest' environment
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
ignorePatterns:
  - lib/
  - dist/
  - node_modules/
  - coverage/
